# Generated by Django 3.2.9 on 2021-11-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_create',
            field=models.DateField(verbose_name='Дата добавления'),
        ),
    ]
