# Generated by Django 3.2.9 on 2021-11-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_data_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.IntegerField(default=128, verbose_name='Память GB'),
        ),
    ]
