# Generated by Django 3.2.9 on 2021-11-21 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211121_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='object_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
