# Generated by Django 3.2.9 on 2021-11-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cartproduct_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
